### ISSUE TITLE
Learn variables and basic types in python

### ISSUE THREAD

**Issue by shovradas** [dassuptirani/competitive-programming#2]
### Tutorials
[Variables](https://www.w3schools.com/python/python_variables.asp)
[Data Types](https://www.w3schools.com/python/python_datatypes.asp)

### More
[Practice](https://www.learnpython.org/en/Variables_and_Types)

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue

**Comment by suptidas** [comment]
Done
