### ISSUE TITLE
Learn python numbers and type casting

### ISSUE THREAD

**Issue by shovradas** [dassuptirani/competitive-programming#3]
### Tutorials
[Numbers](https://www.w3schools.com/python/python_numbers.asp)
[Casting](https://www.w3schools.com/python/python_casting.asp)

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue.

**Comment by shovradas** [comment]
> I would like to work on this issue.

This is just an educational repository not for collaboration at all. Thank you anyways.

**Comment by suptidas** [comment]
The issue has been done properly.
