### ISSUE TITLE
Learn string and boolean in python

### ISSUE THREAD

**Issue by shovradas** [dassuptirani/competitive-programming#4]
### Tutioral
[String](https://www.w3schools.com/python/python_strings.asp),
[Boolean](https://www.w3schools.com/python/python_booleans.asp)

**Comment by suptidas** [comment]
I have studied this issue. 
I haven't understand the "Negative Indexing" part from "Python Strings" tutorial.
And do i need to memorised all the built-in methods in "String Methods" part  from "Python Strings" tutorial?

**Comment by shovradas** [comment]
> I have studied this issue.
> I haven't understand the "Negative Indexing" part from "Python Strings" tutorial.
> And do i need to memorised all the built-in methods in "String Methods" part from "Python Strings" tutorial?

Negative Indexing: We can have a meeting tomorrow to clarify things. see slack
String: no need to memorize all of them. just learn sample usage and let it go. Soon you will be solving problems involving them.

**Comment by suptidas** [comment]
okay ,i get it.
I will be right there.
